homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass-lat
  longitude: !secret hass-long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  whitelist_external_dirs:
    - '/config'
  customize: !include customize.yaml
  #customize_glob: !include customglob.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#  base_url: http://gildebrandhome.duckdns.org/
  base_url: http://192.168.1.21:8123
#    example.duckdns.org:8123
  # trusted_networks:
  #   - 192.168.1.0/16
  #   - 192.168.255.0/24
  #   - 127.0.0.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date

logger:
#  default: info
  default: error
  logs:
  #  homeassistant.components.media_player: debug
  #  homeassistant.components.sensor.scrape: debug
#    homeassistant.components.sensor: warn
    homeassistant.components.automation: debug
    homeassistant.components.light: debug

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

recorder:
  purge_keep_days: 5
  db_url: !secret mariadb_connection_url
  purge_interval: 1
  exclude:
    domains:
      - automation
#      - zwave
      - device_tracker
      - media_player
  include:
    entities:
      - automation.bensinpris
      - automation.dieselpris

#group: !include groups.yaml
group: !include_dir_merge_named groups/

#automation: !include automations.yaml
automation: !include_dir_merge_list automations/

#script: !include scripts.yaml
script: !include_dir_merge_named scripts
python_script:
#input_number: !include_dir_merge_named input_number
input_number:
  bensin:
    name: Bensinpris
    min: 10
    max: 25
    step: 0.01
    mode: box
    unit_of_measurement: 'kr/L'
  diesel:
    name: Dieselpris
    min: 10
    max: 25
    step: 0.01
    mode: box
    unit_of_measurement: 'kr/L'

sensor: !include_dir_merge_list sensors/

influxdb:
  host: 192.168.1.21
  port: 8086
  username: !secret influxdb_user
  password: !secret influxdb_password
  database: homeassistant
  include:
    domains:
      - sensor
  exclude:
    entities:
      - sensor.pihole_ads_blocked_today
      - sensor.eaton3s_status_data
#      - sensor.

#Hardware
zwave:
  usb_path: /dev/ttyACM0

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    home_interval: 10
    exclude:
      - 192.168.1.21
#
  - platform: unifi
    host: 192.168.1.21
    port: 8443
    verify_ssl: false
    username: !secret unifi_user
    password: !secret unifi_password
    detection_time: 300
    monitored_conditions:
      - _last_seen_by_uap
#
  - platform: snmp
    host: 192.168.1.1
    community: !secret snmp_community
    baseoid: !secret snmp_baseoid
#
  - platform: mqtt
    devices:
      emil_mobil_bt: 'hass/device_tracker/emil_mobil/state'
#      emil_mobil_ot: 'owntracks/myggan/oneplus3t'
#owntracks:
 # max_gps_accuracy: 200

# switch:
#   platform: hadockermon
#   host: 192.168.1.21
#   port: 8126
#   stats: true
#   prefix: docker_
#   exclude:
#     - ha-dockermon

# -------------------------------------------------------------------
# *** NOTIFICATIONS ***
notify:
  - platform: pushbullet
    name: pushbullet
    api_key: !secret pushbullet

alert:
  kitchen_window:
    name: 'Köksfönstret öppet'
    entity_id: binary_sensor.kitchen
    state: 'on'
    repeat:
      - 15
      - 30
    skip_first: true
    notifiers:
      - pushbullet

deconz:
  host: 127.0.0.1 #192.168.1.159
  api_key: !secret deconz_apikey #C897371601
  port: 8089

mqtt:
  broker: 192.168.1.21
  port: 1883
  client_id: server
  username: !secret mqtt-user
  password: !secret mqtt-password

cast:
  media_player:
  - host: 192.168.1.152 #Köket 957d765467e46c4543d891667c0ce02
  - host: 192.168.1.66  #Stereo 602724f8c56962aa354e80f90faf46c4

media_player:
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
#     aliases:
#       957d765467e46c4543d891667c0ce02d: 'Kitchen'
#       602724f8c56962aa354e80f90faf46c4: 'Livingroom'
light:
  - platform: switch
    name: TV
    entity_id: switch.tv
# 2018-07-31 22:35:45 DEBUG (SyncWorker_0) [homeassistant.components.media_player.cast] Discovered chromecast ChromecastInfo(host='192.168.1.152', port=8009, uuid='957d7654-67e4-6c45-43d8-91667c0ce02d', model_name='Chromecast Audio', friendly_name='Köket')
# 2018-07-31 22:35:45 DEBUG (SyncWorker_9) [homeassistant.components.media_player.cast] Discovered chromecast ChromecastInfo(host='192.168.1.66', port=8009, uuid='602724f8-c569-62aa-354e-80f90faf46c4', model_name='Chromecast Audio', friendly_name='Vardagsrummet')
# 2018-07-31 22:35:45 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.kitchen, old_state=None, new_state=<state media_player.kitchen=unavailable; friendly_name=Chromecast kök, supported_features=21437 @ 2018-07-31T22:35:45.906224+02:00>>
# 2018-07-31 22:35:45 DEBUG (MainThread) [homeassistant.components.media_player.cast] Connecting to cast device ChromecastInfo(host='192.168.1.152', port=8009, uuid='957d7654-67e4-6c45-43d8-91667c0ce02d', model_name='Chromecast Audio', friendly_name='Köket')
# 2018-07-31 22:35:45 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.livingroom, old_state=None, new_state=<state media_player.livingroom=unavailable; friendly_name=Chromecast stereo, supported_features=21437 @ 2018-07-31T22:35:45.916529+02:00>>
# 2018-07-31 22:35:45 INFO (SyncWorker_1) [pychromecast] Querying device status
# 2018-07-31 22:35:45 DEBUG (MainThread) [homeassistant.components.media_player.cast] Connecting to cast device ChromecastInfo(host='192.168.1.66', port=8009, uuid='602724f8-c569-62aa-354e-80f90faf46c4', model_name='Chromecast Audio', friendly_name='Vardagsrummet')
