title: Home Assistant
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router

views:
    # View tab title.
  - title: Hemma
    icon: mdi:home
    id: home
    # Optional background (overwrites the global background).
    #background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    #theme: dark-mode
    # The cards to show on this view.
    cards:
      - type: vertical-stack
        cards:
        - type: glance
          entities:
            - entity: sensor.presence_emil
              icon: mdi:android
            - entity: sensor.presence_hanna
              icon: mdi:android
        - type: glance
          entities:
            - entity: sensor.temperature_outdoor
            - entity: sensor.temperature_bedroom
            - entity: sensor.temperature_livingroom
            - entity: sensor.temperature_outhouse
        - type: glance
          entities:
            - entity: sensor.12h_outdoor_max
            - entity: sensor.12h_outdoor_mean
            - entity: sensor.12h_outdoor_median
            - entity: sensor.12h_outdoor_min
        - type: glance
          entities:
            - entity: sensor.humidity_outdoor
            - entity: sensor.humidity_bedroom
            - entity: sensor.humidity_livingroom
            - entity: sensor.humidity_outhouse
  - title: Lampor
    icon: mdi:lightbulb
    id: lights
    cards:
      - type: vertical-stack
        cards:
        - type: glance
          title: Lights
          show_header_toggle: true
          entities:
          - entity: switch.tv
            tap_action: toggle
        - type: light
          entity: light.tv
        - type: light
          entity: light.soffan
        - type: light
          entity: light.hornet
        - type: light
          entity: light.framsidan
        - type: light
          entity: light.olles_fonster
  - title: Trafik
    icon: mdi:car
    cards:
      - type: glance
        #title: Bränsle
        entities:
          - entity: input_number.bensin
            name: Bensinpris
            icon: mdi:gas-station
            secondary_info: last-changed
          - entity: input_number.diesel
            name: Dieselpris
            icon: mdi:gas-station
            secondary_info: last-changed
      - type: glance
        title: Vägtemperatur
        columns: 3
        entities:
          - entity: sensor.trafikverket_sandsjobacka_road_temperature
          - entity: sensor.trafikverket_kungsbacka_road_temperature
          - entity: sensor.trafikverket_torpa_road_temperature
          - entity: sensor.trafikverket_stravalla_road_temperature
          - entity: sensor.trafikverket_medelvarde
          - entity: sensor.12h_road_min
      - type: glance
        title: Lufttemperatur
        entities:
        - entity: sensor.trafikverket_sandsjobacka_air_temperature
        - entity: sensor.trafikverket_kungsbacka_air_temperature
        - entity: sensor.trafikverket_torpa_air_temperature
        - entity: sensor.trafikverket_stravalla_air_temperature
  - title: Computers
    icon: mdi:desktop-classic
    cards:
      - type: glance
        title: UPS
        entities:
        - entity: sensor.eaton3s_status
        - entity: sensor.eaton3s_battery_charge
        - entity: sensor.eaton3s_load
      - type: glance
        title: Bandbredd
        entities:
        - entity: sensor.speedtest_download
        - entity: sensor.speedtest_upload
        - entity: sensor.speedtest_ping
      - type: glance
        columns: 3
        title: System
        entities:
        - entity: sensor.memory_use_percent
        - entity: sensor.network_in_enp2s0
        - entity: sensor.network_out_enp2s0
        - entity: sensor.since_last_boot
        - entity: sensor.pihole_ads_blocked_today
        - entity: sensor.hd_temperature_devsde
      - type: glance
        title: Hanna 2TB
        columns: 3
        entities:
        - entity: sensor.hd_temperature_devsda
        - entity: sensor.disk_free_mediahanna2tb
        - entity: sensor.disk_use_percent_mediahanna2tb
      - type: glance
        title: Media 4TB
        columns: 3
        entities:
        - entity: sensor.hd_temperature_devsdb
        - entity: sensor.disk_free_media4tb
        - entity: sensor.disk_use_percent_media4tb
      - type: glance
        title: Backup 4TB
        columns: 3
        entities:
        - entity: sensor.hd_temperature_devsdc
        - entity: sensor.disk_free_mediabackup4tb
        - entity: sensor.disk_use_percent_mediabackup4tb
      - type: glance
        title: Emil 2TB
        columns: 3
        entities:
        - entity: sensor.hd_temperature_devsdd
        - entity: sensor.disk_free_mediaemil2tb
        - entity: sensor.disk_use_percent_mediaemil2tb

      # - type: vertical-stack
      #   cards:
      #   - type: sensor
      #     entity: sensor.bensinpris
      #     name: Bensinpris
      #     hours_to_show: 144
      #     detail: 2
      #     unit: 'kr/l'
      #   - type: entities
      #     title: St1 Lindome
      #     show_header_toggle: true
      #     entities:
      #       - entity: input_number.bensin
      #         name: Bensinpris
      #         icon: mdi:gas-station
      #         secondary_info: last-changed
      #   - type: sensor
      #     entity: sensor.dieselpris
      #     name: Dieselpris
      #     hours_to_show: 144
      #     detail: 2
      #     unit: 'kr/l'
      #   - type: entities
      #     title: St1 Lindome
      #     show_header_toggle: true
      #     entities:
      #       - entity: input_number.diesel
      #         name: Dieselpris
      #         icon: mdi:gas-station
      #         secondary_info: last-changed
