automations:
  name: "Automationer"
  entities:
    - automation.tand_lampor_kl_05
    - automation.slack_lampor_en_timme_efter_soluppgang
    - automation.tand_lampor_innan_solnedgang
    - automation.slack_lampor_kl_24
    - automation.nattsuddare
