  - alias: Get Ungrouped Entities On Start
    hide_entity: true
    trigger:
      platform: homeassistant
      event: start
    action:
      service: python_script.orphans
      data:
        domains_to_ignore: "zone,group,automation,script,zwave"
        target_group: "group.orphans"

  # - alias: 'P1'
  #   initial_state: True
  #   hide_entity: false
  #   trigger:
  #     platform: event
  #     event_type: deconz_event
  #     event_data:
  #       entity_id: button_1
  #       event: 1000
  # #   action:
  # #     service: notify.pushbullet
  # #     data:
  # #       message: "Knapptryck"
  # #       title: "Switch_1"
  # #
  # # - alias: 'Spela P1 i köket'
  # #   trigger:
  # #     platform: event
  # #     event_type: deconz.event
  # #     event_data:
  # #       entity_id: button_1
  # #       event: 1000
  #   action:
  #     - service: notify.pushbullet
  #       data:
  #         title: "Dot button pressed"
  #         message: "Playing SR P1 in kitchen {{states.sensor.time.state}}"
  #     - service: input_select.select_option
  #       data:
  #         entity_id: input_select.radio_station
  #         option: 'SR P1'
  #     - service: input_select.select_option
  #       data:
  #         entity_id: input_select.chromecast_radio
  #         option: 'Köket'
  #     - service: script.turn_on
  #       entity_id: script.radio538

  - alias: 'P1'
    initial_state: True
    hide_entity: false
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        entity_id: button_1
        event: 1000
    action:
      - service: notify.pushbullet
        data:
          title: "Button pressed"
          message: "Playing SR P1 in kitchen {{states.sensor.time.state}}"
      - service: media_player.play_media
        data:
          entity_id: media_player.kitchen
          media_content_id: http://sverigesradio.se/topsy/direkt/132-hi.mp3
          media_content_type: 'audio/mp4'

  - alias: 'P3'
    initial_state: True
    hide_entity: false
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        entity_id: button_1
        event: 1004 #dubbeltryck
    action:
      - service: notify.pushbullet
        data:
          title: "Button pressed"
          message: "Playing SR P3 in kitchen {{states.sensor.time.state}}"
      - service: media_player.play_media
        data:
          entity_id: media_player.kitchen
          media_content_id: http://sverigesradio.se/topsy/direkt/164-hi.mp3
          media_content_type: 'audio/mp4'

  - alias: 'Radio av'
    initial_state: True
    hide_entity: false
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        entity_id: button_1
        event: 1005
    action:
      - service: notify.pushbullet
        data:
          title: "Button pressed"
          message: "Stopping kitchen radio {{states.sensor.time.state}}"
      - service: media_player.turn_off
        data:
          entity_id: media_player.kitchen

#
# - alias: 'Spela P3 i köket'
#   trigger:
#     platform: event
#     event_type: deconz.event
#     event_data:
#       entity_id: button_1
#       event: 1003
#   action:
#     - service: notify.pushbullet
#       data:
#         title: "Dot button pressed"
#         message: "Playing SR P3 in kitchen {{states.sensor.time.state}}"
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.radio_station
#         option: 'SR P3'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.chromecast_radio
#         option: 'Köket'
#     - service: script.turn_on
#       entity_id: script.radio_on
#
# - alias: 'Stoppa radio i köket'
#   trigger:
#     platform: event
#     event_type: deconz.event
#     event_data:
#       entity_id: button_1
#       event: 1004
#   action:
#     - service: notify.pushbullet
#       data:
#         title: "Dot button pressed"
#         message: "Stopping radio in kitchen {{states.sensor.time.state}}"
#     - service: script.turn_on
#       entity_id: script.radio_off
